//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WowClient.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string BtnAccept {
            get {
                return ResourceManager.GetString("BtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Tools.
        /// </summary>
        internal static string BtnAdminTools {
            get {
                return ResourceManager.GetString("BtnAdminTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string BtnCreateAccountText {
            get {
                return ResourceManager.GetString("BtnCreateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Character.
        /// </summary>
        internal static string BtnCreateChar {
            get {
                return ResourceManager.GetString("BtnCreateChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Character.
        /// </summary>
        internal static string BtnDeactivateChar {
            get {
                return ResourceManager.GetString("BtnDeactivateChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Character.
        /// </summary>
        internal static string BtnDeleteChar {
            get {
                return ResourceManager.GetString("BtnDeleteChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string BtnLoginText {
            get {
                return ResourceManager.GetString("BtnLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string BtnLogout {
            get {
                return ResourceManager.GetString("BtnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivate Character.
        /// </summary>
        internal static string BtnReactivateChar {
            get {
                return ResourceManager.GetString("BtnReactivateChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is an Admin.
        /// </summary>
        internal static string ChkAccountIsAdmin {
            get {
                return ResourceManager.GetString("ChkAccountIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net Account Name.
        /// </summary>
        internal static string LblBattleNetAccountText {
            get {
                return ResourceManager.GetString("LblBattleNetAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account Name.
        /// </summary>
        internal static string LblNewAccountNameText {
            get {
                return ResourceManager.GetString("LblNewAccountNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LblPasswordText {
            get {
                return ResourceManager.GetString("LblPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        internal static string StringFactionAlliance {
            get {
                return ResourceManager.GetString("StringFactionAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horde.
        /// </summary>
        internal static string StringFactionHorde {
            get {
                return ResourceManager.GetString("StringFactionHorde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot create an Alliance character, as your active faction is Horde. Delete all Horde characters to create an Alliance character..
        /// </summary>
        internal static string ToolTipAllianceDisabled {
            get {
                return ResourceManager.GetString("ToolTipAllianceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Elf.
        /// </summary>
        internal static string ToolTipBloodElfEnabled {
            get {
                return ResourceManager.GetString("ToolTipBloodElfEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one character of level 55 or higher to create a Death Knight.
        /// </summary>
        internal static string ToolTipDeathKnightDisabled {
            get {
                return ResourceManager.GetString("ToolTipDeathKnightDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Knight.
        /// </summary>
        internal static string ToolTipDeathKnightEnabled {
            get {
                return ResourceManager.GetString("ToolTipDeathKnightEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Worgen or Tauren characters can become Druids.
        /// </summary>
        internal static string ToolTipDruidDisabled {
            get {
                return ResourceManager.GetString("ToolTipDruidDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string ToolTipDruidEnabled {
            get {
                return ResourceManager.GetString("ToolTipDruidEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        internal static string ToolTipGnomeEnabled {
            get {
                return ResourceManager.GetString("ToolTipGnomeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot create a Horde character, as your active faction is Alliance. Delete all Alliance characters to create a Horde character..
        /// </summary>
        internal static string ToolTipHordeDisabled {
            get {
                return ResourceManager.GetString("ToolTipHordeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string ToolTipHumanEnabled {
            get {
                return ResourceManager.GetString("ToolTipHumanEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chosen race cannot be a Mage.
        /// </summary>
        internal static string ToolTipMageDisabled {
            get {
                return ResourceManager.GetString("ToolTipMageDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage.
        /// </summary>
        internal static string ToolTipMageEnabled {
            get {
                return ResourceManager.GetString("ToolTipMageEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.
        /// </summary>
        internal static string ToolTipOrcEnabled {
            get {
                return ResourceManager.GetString("ToolTipOrcEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tauren.
        /// </summary>
        internal static string ToolTipTaurenEnabled {
            get {
                return ResourceManager.GetString("ToolTipTaurenEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chosen race cannot be a Warrior.
        /// </summary>
        internal static string ToolTipWarriorDisabled {
            get {
                return ResourceManager.GetString("ToolTipWarriorDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        internal static string ToolTipWarriorEnabled {
            get {
                return ResourceManager.GetString("ToolTipWarriorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worgen.
        /// </summary>
        internal static string ToolTipWorgenEnabled {
            get {
                return ResourceManager.GetString("ToolTipWorgenEnabled", resourceCulture);
            }
        }
    }
}
