//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowClient.WowServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WowLoginServiceLib", ConfigurationName="WowServiceReference.IWowService")]
    public interface IWowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WowLoginServiceLib/IWowService/Login", ReplyAction="http://WowLoginServiceLib/IWowService/LoginResponse")]
        Common.PlayerData Login(out bool isAdmin, string accountName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WowLoginServiceLib/IWowService/RetrieveAccountCharacters", ReplyAction="http://WowLoginServiceLib/IWowService/RetrieveAccountCharactersResponse")]
        System.Collections.Generic.List<Common.Character> RetrieveAccountCharacters(string accountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WowLoginServiceLib/IWowService/AddCharacterToAccount", ReplyAction="http://WowLoginServiceLib/IWowService/AddCharacterToAccountResponse")]
        bool AddCharacterToAccount(Common.PlayerData playerData, Common.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WowLoginServiceLib/IWowService/CreateAccount", ReplyAction="http://WowLoginServiceLib/IWowService/CreateAccountResponse")]
        bool CreateAccount(string accountName, string password, bool isAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WowLoginServiceLib/IWowService/UpdateCharactersForPlayer", ReplyAction="http://WowLoginServiceLib/IWowService/UpdateCharactersForPlayerResponse")]
        void UpdateCharactersForPlayer(Common.PlayerData playerData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WowLoginServiceLib/IWowService/UpdateCharacterLevels", ReplyAction="http://WowLoginServiceLib/IWowService/UpdateCharacterLevelsResponse")]
        void UpdateCharacterLevels(System.Collections.Generic.List<Common.Character> characters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WowLoginServiceLib/IWowService/RetrieveAllCharacters", ReplyAction="http://WowLoginServiceLib/IWowService/RetrieveAllCharactersResponse")]
        System.Collections.Generic.List<Common.Character> RetrieveAllCharacters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WowLoginServiceLib/IWowService/DeleteCharacterFromAccount", ReplyAction="http://WowLoginServiceLib/IWowService/DeleteCharacterFromAccountResponse")]
        void DeleteCharacterFromAccount(Common.PlayerData playerData, Common.Character character);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWowServiceChannel : WowServiceReference.IWowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WowServiceClient : System.ServiceModel.ClientBase<WowServiceReference.IWowService>, WowServiceReference.IWowService {
        
        public WowServiceClient() {
        }
        
        public WowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.PlayerData Login(out bool isAdmin, string accountName, string password) {
            return base.Channel.Login(out isAdmin, accountName, password);
        }

        public System.Collections.Generic.List<Common.Character> RetrieveAccountCharacters(string accountName)
        {
            return base.Channel.RetrieveAccountCharacters(accountName);
        }
        
        public bool AddCharacterToAccount(Common.PlayerData playerData, Common.Character character) {
            return base.Channel.AddCharacterToAccount(playerData, character);
        }
        
        public bool CreateAccount(string accountName, string password, bool isAdmin) {
            return base.Channel.CreateAccount(accountName, password, isAdmin);
        }
        
        public void UpdateCharactersForPlayer(Common.PlayerData playerData) {
            base.Channel.UpdateCharactersForPlayer(playerData);
        }

        public void UpdateCharacterLevels(System.Collections.Generic.List<Common.Character> characters)
        {
            base.Channel.UpdateCharacterLevels(characters);
        }
        
        public System.Collections.Generic.List<Common.Character> RetrieveAllCharacters() {
            return base.Channel.RetrieveAllCharacters();
        }
        
        public void DeleteCharacterFromAccount(Common.PlayerData playerData, Common.Character character) {
            base.Channel.DeleteCharacterFromAccount(playerData, character);
        }
    }
}
